### PR TITLE
Made Static Site, Removed Python Dependencies, Moved To Docker

### PR DESCRIPTION
**Pull request by bensternthal**

### CODE REVIEW

**Comment by bensternthal** [comment]
@glogiotatidis i based this on your moz.works template and added docker-compose for ease of testing locally. Can you take a look. If all is well I would like you to show me how this gets deployed on deis, will be a good learning exercise for me.

**Comment by glogiotatidis** [comment]
Looks good! :cake:

Send an invite when you're back to go through:
- Deis app creation
- Deploy using `git push`
- Deploy using `deis pull`

Happy thanksgiving !

**Comment by bensternthal** [comment]
Happy days, will do.

**Comment by bensternthal** [comment]
@glogiotatidis oddly I do not have write access to this repo. Can you grant this to me and I will merge.

Much thanks.

**Comment by glogiotatidis** [comment]
I don't have write access either. Maybe @jgmize can help?

**Comment by jgmize** [comment]
@bensternthal, @glogiotatidis you should both have admin access to this repo now.

**Pull request merged**
